### ISSUE TITLE
TS7006: Parameter 'e' implicitly has an 'any' type (not covered by 105)

### ISSUE THREAD

**Issue by PartyArk** [brandonroberts/angular-router-loader#108]
This is a continuation of #105 (closed) but not fixed in 0.8.4

The issue is with line 27 of utils.js

`    '  }, function(e) {',`

should be

`    '  }, function(e:any) {',`

Thanks!

**Comment by PartyArk** [comment]
Hi I'm unable to do a PR, but I've fixed the code in (my) source and it works. I've also scanned the code for other untyped variables and there don't seem to be any.

**Comment by pedromosquerat** [comment]
@PartyArk 
I've just created a pull with the suggested fix.

**Comment by brandonroberts** [comment]
Thanks @pedromosquerat! I left a comment on the PR

**Comment by brandonroberts** [comment]
Fix published as `0.8.5`. Thanks @pedromosquerat and @PartyArk for your help!
