### ISSUE TITLE
es compatibility

### ISSUE THREAD

**Issue by atiertant** [brandonroberts/angular-router-loader#19]
hi, could you replace src/utils.js Line 25
-    '  (require as any).ensure([], function (require: any) {',  
-    '  require.ensure([], function () {',

to be compatible with javascript? (don't know if it work with typescript)

**Comment by brandonroberts** [comment]
This will break TypeScript because there will be missing support for `require.ensure` conflicting with node typings. I could add an option to the loader for a vanilla javascript version of the load string.

**Comment by brandonroberts** [comment]
If you're using Webpack 2, you can use the `loader=system` option

**Comment by atiertant** [comment]
@brandonroberts i use webpack 1 ...

**Comment by brandonroberts** [comment]
It still works with Webpack 1 if you're using TypeScript. Will you provide a reproduction in a gist or repo?

**Comment by atiertant** [comment]
@brandonroberts i wouldn't like to support an es version, i would prefer contribute to your...
i forked just to add my repo in my package.json for now, if you wouldn't like support es compatibility, i'll push it on npm.

**Comment by brandonroberts** [comment]
I would like to support your issue as well. My question is are you using TypeScript or not?

**Comment by atiertant** [comment]
no, i'm using javascript

**Comment by brandonroberts** [comment]
I haven't forgotten about your issue. Would it be sufficient to check the file extension in order to determine whether to add the type? If the extension is `ts`, use `require as any`. If its `js`, just use `require`. What do you think?

**Comment by atiertant** [comment]
@brandonroberts looks a good idea

**Comment by ayyash** [comment]
I used loader=system, it generates the right line but in production I get the error EXCEPTION: Uncaught (in promise): ReferenceError: System is not defined
I am not sure if default loader would produce this error (haven't got this far), the main setup I have is that I use systemjs throughout development, and I only webpack everything from the js files before production, so I do not reference the ts transpiler in webpack at all, the tsc I use already produced the required js files. So, that being said, the output cannot have "typescript" or "es6" specific statements... is that even possible in this case?

**Comment by vepasto** [comment]
@brandonroberts @atiertant Check my pull request. It adds ES support by query parameter. What you think?

**Comment by atiertant** [comment]
@vepasto couldn't we use @brandonroberts solution?
with something like `var es = filePath.endsWith('.js');` in getRequireLoader function ?

**Comment by vepasto** [comment]
Is it reliable enough since TS project can contain .js files?

**Comment by atiertant** [comment]
@vepasto what kind of .js file in a TS project can contain a loadChildren ? see https://github.com/Microsoft/TypeScript/issues/2302

**Comment by vepasto** [comment]
@atiertant I'm not sure. To be honest I'm not very familiar with TS. It just sounded dangerous as we're making potentially backwards incompatible changes, and someone's build could possibly break. That's why I suggested the _safe_ way.

If you suggest it is safe, can you make a pull request?

**Comment by vepasto** [comment]
Is anyone going to make that pull request? @atiertant @brandonroberts

**Comment by atiertant** [comment]
@vepasto will not have time for now, @brandonroberts do you think https://github.com/brandonroberts/angular-router-loader/issues/66 could be merged ?

**Comment by brandonroberts** [comment]
Support for plain JS files released as `0.6.0`
