### ISSUE TITLE
How to control lazy loading?

### ISSUE THREAD

**Issue by Sri276286** [brandonroberts/angular-router-loader#31]
Hi,

I have a requirement in which I refer to a module(which is only called but not defined)  from a different folder on the server.

Let me be clear:

Party A : calls loadChildren: ./someModule#SomeModule

Party B:  defines that module

Things I am trying to achieve : 

1. Can I try to have something where numbers are not given in order of it's loading(Instead of orders any other readable names.)
2. I want to develop a chunk(bundled) that can be simply used in another project by loadChildren(of that project) - referring to this bundled chunk.

Please let me know if more clarification needed.

I want to know if 2nd thing which I want can be achieved with webpack.

Note : I understood lazyloading is taken care by angular2-router-loader.

**Comment by brandonroberts** [comment]
1. You can have named chunks, which will be used instead of the default naming scheme for lazy loaded chunks.
2. That is outside the scope of this loader. If you want to create a reusable module to be used in another project, you're essentially creating a third-party library.
