### ISSUE TITLE
How to handle lazy loading failure when offline?

### ISSUE THREAD

**Issue by angeor2** [brandonroberts/angular-router-loader#38]
Hi, I'm using angular 2 lazy routing. Client is bundled with webpack2 using AOT and angular-router-loader to lazy load children. Normally everything works as expected.
However if I emulate being disconnected (e.g by using the Offline chrome developer tools option) routing fails, as expected, because it can't load the relevant chunk. The error is 'Loading chunk [chunk number] failed'
However after that no routing command works, it's like the router gets broken.
Tried to reproduce the issue in jit, but in no effort, router continues to work then. Perhaps this is something angular-router-loader could handle?
Is there anything we can do to stop the router from breaking after the lazy load fails? I opened a [stackoverflow question](http://stackoverflow.com/questions/41164968/how-to-handle-angular2-lazy-loading-route-failure), no feedback yet.

Thank you

**Comment by brandonroberts** [comment]
This seems like a router issue and not an issue with the loader since it works in JIT and not AOT. The loader is only responsible for creating the code splitting points and resolving the lazy loaded module.

**Comment by angeor2** [comment]
Thank you for your answer. I'll report back if I find something

**Comment by angeor2** [comment]
Seems to be a known angular2 issue: [https://github.com/angular/angular/issues/12289](https://github.com/angular/angular/issues/12289)

**Comment by kblestarge** [comment]
Hi @angeor2, I am experiencing the same problem. Were you able to find a good workaround? I'm in desperate need of a solution.
