### ISSUE TITLE
doesn't work out in dynamic-reactive froms

### ISSUE THREAD

**Issue by JeffreyChan** [brandonroberts/angular-router-loader#40]
The error pic is here:
![image](https://cloud.githubusercontent.com/assets/5321225/21381868/b67f947e-c798-11e6-8f9c-18c0db39997d.png)

one component in my sub routes is dynamic-reactive-forms.

> 

<h1>
    Customer Dynamic Static Form Reactive</h1>
<form [formGroup]="customerForm" (ngSubmit)="onSubmit()">
    <div class="form-group">
        <label for="name">Name</label>

        <input type="text" id="name" class="form-control" formControlName="name">

        <div *ngIf="formErrors.name" class="alert alert-danger">
            {{ formErrors.name }}
        </div>

    </div>

    <div formArrayName="addresses">
        <div *ngFor="let address of addressesFormArray.controls; let i=index" class="panel panel-default">
            <div class="panel-heading">
                <span>Address {{i + 1}}</span>
                <span class="glyphicon glyphicon-remove pull-right" *ngIf="addressesFormArray.controls.length > 1" (click)="removeAddress(i)"></span>
            </div>
            <div class="panel-body" [formGroupName]="i">
                <address [group]="address" [addressError]="addressErrors[i]"></address>
            </div>
        </div>
    </div>

    <div class="margin-20">
        <a (click)="addAddress()" style="cursor: default"> Add another address +
</a>
</div>

<div class="margin-20">
    <button type="submit" class="btn btn-primary pull-right" [disabled]="!customerForm.valid">Submit</button>
</div>
<div class="clearfix"></div>

<div class="margin-20">
    <div>myForm details:-</div>
    <pre>Is myForm valid?: <br>{{customerForm.valid | json}}</pre>
    <pre>form value: <br>{{customerForm.value | json}}</pre>
</div>
</form>

nodejs version : 6.92
OS: WIN 7 X64
The others:
![image](https://cloud.githubusercontent.com/assets/5321225/21381937/0bda8ef6-c799-11e6-8b32-d0b3073d5d70.png)

**Comment by brandonroberts** [comment]
This error has nothing to do with lazy loaded modules.

**Comment by JeffreyChan** [comment]
but the component in sub route won't work, in root route will work fine? How is it happen?

**Comment by brandonroberts** [comment]
Most likely your lazy loaded module is missing an import that provides that directive or binding.

**Comment by JeffreyChan** [comment]
It can't be. I just use gulp run ,everything is okay.
here is [source code](https://github.com/JeffreyChan/angluar2-best-practice)
would you take your time to run?
It' won't take you long time, please help me.

**Comment by JeffreyChan** [comment]
hi brandon, thanks a lot. I think you are right.
