### ISSUE TITLE
Doesnt work on resetConfig when use delay

### ISSUE THREAD

**Issue by Fresst10** [brandonroberts/angular-router-loader#42]
Hello, I try it code.

ngOnInit() {
    var self = this;
    setTimeout(function(){
      self.setRouters();
    },200);
  }

  setRouters(){
    let resetRouters = [];
    resetRouters.push({
      path: 'home', loadChildren: () => System.import('./home').then((comp: any) => comp.default)
    });
    this.router.resetConfig(resetRouters);
  }

Without delay it work. But when i do delay, try 'resetConfig' after success xmlhttp request or relove of proimse it doesnt work.

Thx.

**Comment by brandonroberts** [comment]
This is not for router support. It's for bugs and issues with the loader
