### ISSUE TITLE
The regex for loadChildren misses a case

### ISSUE THREAD

**Issue by ayyash** [brandonroberts/angular-router-loader#43]
this regex to catch loadChildren `var loadChildrenRegex = /loadChildren[\s]*:[\s]*['|"](.*?)['|"]/gm;`
does not catch loadChildren that do not use strings, or prefix with a variable like what I do:

`loadChildren: config.moduleUrl + 'modulename#ModuleName';`

**Comment by brandonroberts** [comment]
This is intentional. The loader is doing a string replacement, so if you're using variables or functions in the loadChildren value it's going to skip it.

**Comment by ayyash** [comment]
why is it skipping it? whats the side effect?

**Comment by brandonroberts** [comment]
The string replacement is static. Code isn't going to be evaluated before the loader does the replacement since it won't be evaluated until runtime.
