### ISSUE TITLE
Load routes from external file

### ISSUE THREAD

**Issue by tettusud** [brandonroberts/angular-router-loader#47]
Hi 
 How can I lazy load routes from external file.I didn't quiet get if I can achieve it using chunkName option 
  Could you point me to an example

**Comment by brandonroberts** [comment]
This loader is for create code splitting points for lazy loading at compile time. If you want to load routes at runtime, you need to look into the `resetConfig` function in the `Router` service.

https://angular.io/docs/ts/latest/api/router/index/Router-class.html#!#resetConfig-anchor
