### ISSUE TITLE
[docs] clarification on genDir option

### ISSUE THREAD

**Issue by GiuseppePiscopo** [brandonroberts/angular-router-loader#49]
In [options doc page](https://github.com/brandonroberts/angular-router-loader/blob/master/docs/options.md#gendir-default-) it is mentioned that if you set the `angularCompilerOptions.genDir` option in `tsconfig.json`, then the `genDir` option in loader

> [...] needs to be set to the relative path to your application directory.

Just expanding on example provided in docs, the structure (after an AOT build) should look like:

```
|--+ compiled\
   `--+ src\
      `--- app\

|--+ src\
   `--- app\

|-- tsconfig.json
```

Is it correct that the option value in loader should be **exactly** the same as in `tsconfig.json`? If that's true, would you be ok with a PR adding such clarification to the doc?

If that's not correct, could you please explain a bit more the rationale? Is *application directory* the path where `package.json` and others are located? Or the path where source code entry point is located? Or else?

Thanks a lot

**Comment by brandonroberts** [comment]
@GiuseppePiscopo You're correct. I recently merged in some changes so the two genDir values could match but didn't update the docs yet. I would definitely be ok with a PR clarifying that. 

Thanks
