### ISSUE TITLE
can't resolve lazyload.module.ngfactory

### ISSUE THREAD

**Issue by zhaxi** [brandonroberts/angular-router-loader#50]
AOT build process shows:
![image](https://cloud.githubusercontent.com/assets/4652360/21756651/dd57aa12-d65e-11e6-9ca9-dfa0df882c1c.png)

ngfactory files were generated in aot dir, not compile dir

Is it related to angualr-router-loader(latest 0.5.0 also failed)?

Enviroments: Angular 2.4.1, Webpack 2.1.0-beta.27

**Comment by brandonroberts** [comment]
Your `genDir` option needs to be set to `aot` to match the directory where your ngfactory files were generated.

`angular-router-loader?aot=true&genDir=aot`

**Comment by zhaxi** [comment]
@brandonroberts It works, could pls upload 0.5.0 to npm asap?

**Comment by brandonroberts** [comment]
`0.5.0` is already on npm
