### ISSUE TITLE
Webpack Loader

### ISSUE THREAD

**Issue by DoubleExposure** [brandonroberts/angular-router-loader#53]
hi Brandon, I am having a problem with the Loader.
I am trying to integrate Dan Whalin's Customer Manager code with ASP.NET Core + Angular 2 template for Visual Studio.
When trying to lazyLoad the module, it is failing. Since I am new to Angular2 maybe you can assist me. Would you mind looking at the Code that I created? I can share it via OneDrive. I am really stuck. Thanks

**Comment by brandonroberts** [comment]
Are you still having an issue with the loader? If you can paste your routing setup code I may be able to assist.
