### ISSUE TITLE
Add ability to specify chunk name

### ISSUE THREAD

**Issue by bekos** [brandonroberts/angular-router-loader#56]
Based on [webpack's docs](https://webpack.js.org/guides/code-splitting-require/) there is the ability to specify chunk's name on `require.ensure`.
```js
require.ensure(dependencies: String[], callback: function(require), chunkName: String)
```

Can this lbrary's API be extended like this?
```js
loadChildren: './lazy.module#LazyModule?sync=true&chunkName=lazy'
```

Thx for your effort 👍

**Comment by brandonroberts** [comment]
Here you go: https://github.com/brandonroberts/angular-router-loader/blob/master/docs/options.md#chunkname-require-loader-only

**Comment by bekos** [comment]
Oops! Great and sorry for the noise :-)
