### ISSUE TITLE
Lazy loading not working with webpack 2

### ISSUE THREAD

**Issue by ravimittal16** [brandonroberts/angular-router-loader#57]
Hi,

I am facing an issue, [check it out here](https://stackoverflow.com/questions/42142795/lazy-loading-modules-angular-2-and-asp-net-core). Lazy loading not working if i use this package. Webpack to updated its configuration strategies. 

Could you please help me it because right now it seems a show stopper for me. 

HIGH PRIORITY

**Comment by brandonroberts** [comment]
This repo should have what you are looking for in lazy loading with dot net core https://github.com/damienbod/Angular2WebpackVisualStudio

**Comment by ravimittal16** [comment]
okay i will check that 

thanks for the update
