### ISSUE TITLE
Having a different base href results in wrong chunk URLs

### ISSUE THREAD

**Issue by carlescs** [brandonroberts/angular-router-loader#60]
I have a base href different from '/' . For example, in my layout I have:

`<base href="/Test/">`

Then, when trying to async load my chunks, it prefixes the url with `/Test/`, even though my scripts are being generated on the /Scripts/js/ folder.

Is there any way to fix this?

Thanks.

**Comment by brandonroberts** [comment]
This is outside the scope of this loader. Its only responsible for finding lazy loaded chunks at build time. That's standard browser behavior to load the files from the base href path. If your base href is at `/Test/`, then you'll need to deploy your bundled files in that same path.

**Comment by carlescs** [comment]
Thanks @brandonroberts . For the record, I got it working by removing the `/Test` from the base href and adding it to the routes. It's far from ideal, but it allows my scenario.

**Comment by brandonroberts** [comment]
Cool. You can also set the base href just the for app itself: https://angular.io/docs/ts/latest/api/common/index/APP_BASE_HREF-let.html
