### ISSUE TITLE
AOT compilation

### ISSUE THREAD

**Issue by tonimitrevski** [brandonroberts/angular-router-loader#63]
Hi All. Please tell me what i wrong here, I want to compiling with AOT
![screenshot_1](https://cloud.githubusercontent.com/assets/15773773/23655892/7fa86ffe-0337-11e7-92a0-d39ad38ae969.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/15773773/23655891/7fa6d964-0337-11e7-91b5-fb67024c5704.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/15773773/23655890/7fa694fe-0337-11e7-9ba4-fcd194dce8ba.png)

**Comment by tonimitrevski** [comment]
Wher i go with this example
https://github.com/brandonroberts/angular-router-loader/blob/master/docs/options.md#general-loader-options

throw me error 
![screenshot_4](https://cloud.githubusercontent.com/assets/15773773/23656137/b6c9b226-0338-11e7-99f6-81de10ee52ed.png)

**Comment by tonimitrevski** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/15773773/23656155/cfea0d32-0338-11e7-9a86-d7b9b803ea16.png)

with this option

**Comment by brandonroberts** [comment]
The loader does the replacement for you, you don't need to paste and edit the code yourself. If you leave it as `loadChildren: 'path/to/feature.module#FeatureModule'`

**Comment by tonimitrevski** [comment]
It's ok, now i have problem with path
![screenshot_1](https://cloud.githubusercontent.com/assets/15773773/23659630/045ec27a-0347-11e7-90a5-287c9ab26f0a.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/15773773/23659632/04609d2a-0347-11e7-805b-09ba3874020b.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/15773773/23659631/0460af9a-0347-11e7-8fa1-b17fe352d5b5.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/15773773/23659636/067c912c-0347-11e7-9797-ce8456b6e449.png)

**Comment by tonimitrevski** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/15773773/23659655/18bbe644-0347-11e7-98d0-7eb839ba6fc3.png)

**Comment by brandonroberts** [comment]
You should be using `angular-router-loader` version `0.5.0` and not `angular2-router-loader`

**Comment by tonimitrevski** [comment]
Thank you very much
