### ISSUE TITLE
Loader not working in case of aot with webpack

### ISSUE THREAD

**Issue by aditya1122** [brandonroberts/angular-router-loader#65]
Hi

I have installed it using npmjs:   "angular-router-loader": "^0.5.0",

My tsconfig.aot.js:

    {
    "compilerOptions": {
        "module": "es2015",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
         "outDir": "./dist"
    },
    "exclude": [
        "node_modules",
        "dist",
        "src/environments"
    ],
    "angularCompilerOptions": {
        "skipMetadataEmit": true
    }
    }

I am using webpack. In webpack.config.prod.js:

    module: {
        loaders: [{
            test: /\.ts$/,
            loaders: [
                'awesome-typescript-loader',
                'angular2-template-loader',
                'angular-router-loader?aot=true&genDir=dist/src/etpapp/app'
            ]
        }]
    },

In my routing file, I have done this:

    export const ROUTES: Routes = [
        { path: '', component: HomeComponent },
        {
            path: 'users',
            loadChildren: () => new Promise(function (resolve) {
                (require as any).ensure([], function (require: any) {
                    resolve(require('./users/user.module.ngfactory')['UserModuleNgFactory']);
                });
            })
        },
        { path: 'list', component: ListComponent }
    ];

    @NgModule({
        imports: [ RouterModule.forRoot(ROUTES) ],
        exports: [ RouterModule ]
    })
    export class AppRoutingModule {
    }

    export const routingComponents = [
        HomeComponent,
        ListComponent
    ];

My users.routing.ts

    import { Routes, RouterModule } from "@angular/router";
    import { UserComponent } from "./user.component";
    const USER_ROUTES: Routes = [
        { path: '', component: UserComponent }
    ];
    export const userRouting = RouterModule.forChild(USER_ROUTES);

The error generated is:
         Error: Error encountered resolving symbol values statically. Function calls are not supported.     Consider replacing the function o
r lambda with a reference to an exported function (position 78:21 in the original .ts file), resolving symbol ROUTES in C:/Users
/adg/Documents/Visual Studio Code/etestpoint/src/etpapp/app/app-routing.module.ts, resolving symbol AppRoutingModule in C:/Users
/adg/Documents/Visual Studio Code/etestpoint/src/etpapp/app/app-routing.module.ts, resolving symbol AppRoutingModule in C:/Users
/adg/Documents/Visual Studio Code/etestpoint/src/etpapp/app/app-routing.module.ts, resolving symbol AppRoutingModule in C:/Users
/adg/Documents/Visual Studio Code/etestpoint/src/etpapp/app/app-routing.module.ts
    at positionalError (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\compiler.umd
.js:25944:39)
    at simplifyInContext (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\compiler.u
md.js:25781:31)
    at StaticReflector.simplify (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\com
piler.umd.js:25795:17)
    at StaticReflector.annotations (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\
compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\com
piler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\c
ompiler\bundles\compiler.umd.js:18272:64)
    at addNgModule (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\compiler.umd.js:
25053:62)
    at C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\compiler.umd.js:25064:18
    at Array.forEach (native)
    at _createNgModules (C:\Users\adg\Documents\Visual Studio Code\etestpoint\node_modules\@angular\compiler\bundles\compiler.um
d.js:25063:30)
Compilation failed

Please help me solve the issue.

**Comment by mbenzenhoefer** [comment]
You need to put your function in loadChildren externally. see https://github.com/angular/angular/issues/11262

**Comment by aditya1122** [comment]
Thanks. It solved my issue.
