### ISSUE TITLE
Debug always enabled

### ISSUE THREAD

**Issue by bruno-serfe** [brandonroberts/angular-router-loader#67]
Hey guys the debug is always enabled, I'm trying to pass the following configuration:

```
{
  test: /\.ts$/,
      loaders: [
           'angular-router-loader?debug=false'
      ]
}
```

https://webpack.github.io/docs/using-loaders.html

But the debug is still appearing in console. Any suggestions?

Also after install the loader forcing v0.5.0 it says:

── angular-router-loader@0.5.0  invalid

**Comment by brandonroberts** [comment]
Can you share more of your webpack config?
