### ISSUE TITLE
Lazy loading destination directory

### ISSUE THREAD

**Issue by hugobluefuse** [brandonroberts/angular-router-loader#70]
Hi,
I currently have my scripts in a js folder. But when using this loader, I get 404's because the app is not looking for the bundle on the js folder. Is there an option I can set to the loader so it fetches the bundle on a different directory?

PS: My app is currently not running AOT

**Comment by brandonroberts** [comment]
This loader does not handle where the files are loaded at runtime. You would need to deploy those files in the appropriate folder yourself. See https://github.com/brandonroberts/angular-router-loader/issues/60

**Comment by hugobluefuse** [comment]
Issue #60 is unrelated.

Webpack successfully deploys the files to /js because I specifically tell it to:
`output: {
        path: resolve('./public/js'),
        filename: '[name].bundle.js'
    },`

So the bundles generated will go to the appropriate files. Is there a way to, at runtime, grab them from the appropriate folder? 
I understand that the loader might not handle it, but can you assist?

Thanks

**Comment by brandonroberts** [comment]
Have you tried changing your application base href to `/js/` instead of the base href used in  your index.html

https://angular.io/docs/ts/latest/api/common/index/APP_BASE_HREF-let.html
