### ISSUE TITLE
ERROR in Step1Module?loader=system

### ISSUE THREAD

**Issue by gorshkov-leonid** [brandonroberts/angular-router-loader#71]
```
   "loaders": [
                    "angular-router-loader?sync=true&aot=true&genDir=compiled&debug=true",
                    "@ngtools/webpack"
    ]
```

After I used query parameters
```
{path: "step1", loadChildren: "./step1/step1.module#Step1Module?loader=system"},
```
, I got error: ` ERROR in Step1Module?loader=system is not an NgModule`

This does not work too: `{path: "step1", loadChildren: "./step1/step1.module#Step1Module?chunkName=Step1Module"},`
 

Angula 4, Is it bug?

**Comment by brandonroberts** [comment]
Since you're using @ngtools/webpack you don't need angular-router-loader

**Comment by gorshkov-leonid** [comment]
Ok, thank you. I thought that it can be related with problem https :// github.com/ angular/ angular/ issues/ 10958 and decide to answer.
