### ISSUE TITLE
ERROR : Could not resolve es6-promise-loader when loading lazily loaded module from node_modules using AOT with webpack

### ISSUE THREAD

**Issue by vkvarma** [brandonroberts/angular-router-loader#74]
ERROR in Could not resolve "es6-promise-loader?,[name]!../node_modules/test/test.module" from "app/app.module.ts".

compilation failed only and its generates the output minified js which is working fine when using with lite-server.
Please let me know why compilation failed ..........

**Comment by vikikamath** [comment]
@vkvarma were you able to find some resolution ?

**Comment by vkvarma** [comment]
i started using  "angular2-load-children-loader",
                "light-ts-loader" with webpack

**Comment by vkvarma** [comment]
not able to used with systemjs in that case of lazy loading , but i found a way to do this
