### ISSUE TITLE
False positive "loadChildren" regular expression match

### ISSUE THREAD

**Issue by pglazkov** [brandonroberts/angular-router-loader#81]
The regular expression for replacing `loadChildren` matches any string in the following format:
```
loadChildren: 'xxx'
```
This causes a problem with [angular-tree-component](https://github.com/500tech/angular-tree-component) when compiling the app with AOT. This is because that component has [`loadChildren` property](https://github.com/500tech/angular-tree-component/blob/master/lib/components/tree.component.ts#L100) property and AOT produces an `ngfactory.ts` file that contains `loadChildren: 'loadChildren'` that gets replaced by the loader causing the compilation to fail.

This can be fixed by changing the regular expression to include the `#` symbol (since all lazy routes seem to require the module name separated by that symbol):
```
loadChildren[\s]*:[\s]*['|"](.*#{1}.*)['|"]
```

**Comment by brandonroberts** [comment]
I'll look into this soon. I'd be hesitant to force you to include the `#` in the `loadChildren` string because its not actually required. Its preferred because it works with AOT.

**Comment by brandonroberts** [comment]
Closing this as the library mentioned has renamed the `loadChildren` property, so the conflict no longer exists.
