### ISSUE TITLE
can't handle loadChildren correctly.

### ISSUE THREAD

**Issue by mrdulin** [brandonroberts/angular-router-loader#85]
compare these two ways: 

```ts
// loadChildren: loadListModule  //<- can't handle this correctly. How can I handle this?
loadChildren: './+list/list.module#ListModule?chunkName=ListModule' //<- handle correctly
```

`+list/List.module.ts`: 
```ts
...
export class ListModule { }

export function loadListModule() {
  return ListModule;
}
```

The first way, `aot` is fine. But when you build with `webpack` and run app, the chrome console will give an error: 

I ask the question here: https://stackoverflow.com/questions/45713345/angular2-runtime-compiler-is-not-loaded

**Comment by brandonroberts** [comment]
Use the `sync=true` option for loading modules synchronously instead of lazily: https://github.com/brandonroberts/angular-router-loader#synchronous-loading

**Comment by mrdulin** [comment]
@brandonroberts ok. it that meanings my way is not support?

**Comment by brandonroberts** [comment]
Yes. The `sync` option does what you need.

**Comment by brandonroberts** [comment]
Your way won't work with AoT

**Comment by mrdulin** [comment]
@brandonroberts thanks.
