### ISSUE TITLE
angular-router-loader not working with latest version of loader-utils 1.1.0

### ISSUE THREAD

**Issue by naveedahmed1** [brandonroberts/angular-router-loader#86]
I tried adding angular-router-loader with loader-utils 1.1.0 to my app but its throwing below error:

```
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: Error: Module build failed: TypeError: loaderUtils.getOptions is not a function
```

**Comment by brandonroberts** [comment]
I don't think this is an issue with this loader. You may have another package that depends on an older version of `loader-utils` that is getting installed.
