### ISSUE TITLE
how can I lazyload modules with two Components?

### ISSUE THREAD

**Issue by Reboca** [brandonroberts/angular-router-loader#87]
because of need seting default path:'', lazyload modules always go default component.
![image](https://user-images.githubusercontent.com/21053764/30307466-e976a2ee-97b0-11e7-9717-4b81f3f1267f.png)
![image](https://user-images.githubusercontent.com/21053764/30307470-ed610674-97b0-11e7-85cb-f288e3c0f602.png)

how can I don't need to set default path?

**Comment by brandonroberts** [comment]
Order matters in the routing configuration, so you need to place `map` above your empty path route to load its module. Then your map routes is just an array of child routes.
