### ISSUE TITLE
npm package fails to install

### ISSUE THREAD

**Issue by coffeymatt** [brandonroberts/angular-router-loader#88]
I'm trying to do this with the latest version of angular-router-loader:
http://fiyazhasan.me/lazy-loading-ngmodules-in-asp-net-core-angularspa/

But the npm package fails to install on windows 10 x64 in latest visual studio 2017.

npm -v = 3.10.10

Error message in output:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\npm.CMD" install
npm WARN install Couldn't install optional dependency: Unsupported
WebClientTemplate@0.0.0 C:\Users\Matty\source\repos\CoffeyIdentityServer\WebClientTemplate
└── angular-router-loader@0.6.0

**Comment by brandonroberts** [comment]
I suggest updating to a newer version of npm
