### ISSUE TITLE
angular 5 AOT chnages breaking route lazy loading 

### ISSUE THREAD

**Issue by MashB** [brandonroberts/angular-router-loader#91]
GenDIr is no more hounored by Angular 5 now .. can you please update code to handle the Angular 5 scenario ?

**Comment by brandonroberts** [comment]
Yep

**Comment by MashB** [comment]
@brandonroberts Awesome Job , its working now.

**Comment by Aralhi** [comment]
With in angular 5. I config webpack.config.js according to the doc. But it cannot webpack router to dust. It seems to the webpack will works well after I delete all of the “genDir” in the project. Did I miss something else? Thanks!
